<a href="https://colab.research.google.com/github/jihyeon602/DeepLearning_practice/blob/main/2_%EC%8B%A0%EA%B2%BD%EB%A7%9D%EA%B8%B0%EB%B3%B8%EA%B5%AC%EC%84%B1%EC%9A%94%EC%86%8C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 2. 신경망 기본 구성 요소

__감사말__

프랑소와 숄레의 [Deep Learning with Python, Second Edition](https://www.manning.com/books/deep-learning-with-python-second-edition?a_aid=keras&a_bid=76564dff) 2장에 사용된 코드에 대한 설명을 담고 있으며 텐서플로우 2.6 버전 이상에서 작성되었습니다. 소스코드를 공개한 저자에게 감사드립니다.

__구글 코랩 설정__

'런타임 -> 런타임 유형 변경' 메뉴에서 GPU를 지정한다.
TensorFlow 버전을 확인하려면 아래 명령문을 실행한다.

In [1]:
import tensorflow as tf
tf.__version__
# /content

'2.18.0'

TensorFlow가 GPU를 사용하는지 여부를 확인하려면 아래 명령문을 실행한다.
아래와 같은 결과가 나오면 GPU가 제대로 지원됨을 의미한다.

```
[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
```

In [ ]:
tf.config.list_physical_devices('GPU')

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

**참고**

아래 코드에 대한 자세한 설명은
[신경망 구성 요소](https://codingalzi.github.io/dlp2/building_blocks_of_NN.html)를
참고한다.

## 신경망 모델 기초 훈련법

**케라스로 MNIST 데이터셋 불러오기**

In [ ]:
from tensorflow.keras.datasets import mnist
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


훈련셋 정보

In [ ]:
train_images.shape # (batch, h, w)

(60000, 28, 28)

In [ ]:
len(train_labels)

60000

In [ ]:
train_labels

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

테스트셋 정보

In [ ]:
test_images.shape

(10000, 28, 28)

In [ ]:
len(test_labels)

10000

In [ ]:
test_labels

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

**신경망 모델의 구조 지정**

In [ ]:
from tensorflow import keras
from tensorflow.keras import layers

model = keras.Sequential([
    layers.Dense(512, activation="relu"), # 음수면 => 0
    layers.Dense(10, activation="softmax") # 확률의 합을 1로 만들어 주는 함수
])

**신경망 모델 컴파일**

In [ ]:
model.compile(optimizer="rmsprop",
              loss="sparse_categorical_crossentropy",
              metrics=["accuracy"])

**이미지 데이터 전처리**

In [ ]:
train_images = train_images.reshape((60000, 28 * 28)) # flatten => 784
train_images = train_images.astype("float32") / 255   # 0과 1사이의 값
test_images = test_images.reshape((10000, 28 * 28))
test_images = test_images.astype("float32") / 255     # 0과 1사이의 값

**검증셋 지정**

In [ ]:
val_images = train_images[:10000]    # 검증셋. 샘플 1만 개
train_images = train_images[10000:]  # 훈련셋. 샘플 5만 개

val_labels = train_labels[:10000]    # 검증셋 타깃
train_labels = train_labels[10000:]  # 훈련셋 타깃

**모델 훈련**

In [ ]:
model.fit(train_images,
          train_labels,
          epochs=10,
          batch_size=128,
          validation_data=(val_images, val_labels))

Epoch 1/10
391/391 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.8665 - loss: 0.4666 - val_accuracy: 0.9551 - val_loss: 0.1556
Epoch 2/10
391/391 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.9619 - loss: 0.1328 - val_accuracy: 0.9664 - val_loss: 0.1127
Epoch 3/10
391/391 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9765 - loss: 0.0793 - val_accuracy: 0.9746 - val_loss: 0.0866
Epoch 4/10
391/391 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9838 - loss: 0.0561 - val_accuracy: 0.9727 - val_loss: 0.0939
Epoch 5/10
391/391 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9875 - loss: 0.0427 - val_accuracy: 0.9766 - val_loss: 0.0785
Epoch 6/10
391/391 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.9912 - loss: 0.0313 - val_accuracy: 0.9780 - val_loss: 0.0732
Epoch 7/10
391/391 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.9944 - loss: 0.0223 - val_accuracy: 0.9793 - val_loss: 0.0723
Epoch 8/10
391/391 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9956 - loss: 0.0180 - val_accuracy: 0.

## 훈련된 모델 활용과 평가

**모델 활용: 예측하기**

In [ ]:
test_digits = test_images[0:10]
predictions = model.predict(test_digits)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 253ms/step


0번 이미지에 대한 예측값

In [ ]:
predictions[0]

array([2.6727984e-09, 1.8644722e-10, 4.8377541e-07, 4.1036943e-05,
       8.9908484e-13, 3.8451148e-10, 1.7759259e-13, 9.9995339e-01,
       3.3493788e-09, 5.1417915e-06], dtype=float32)

가장 높은 확률값을 갖는 인덱스는 7.

In [ ]:
predictions[0].argmax() # 7번

7

0번 이미지가 가리키는 숫자가 7일 확률이 99.98% 정도.

In [ ]:
predictions[0][7]

np.float32(0.9999534)

실제로 첫째 이미지의 레이블이 7임.

In [ ]:
test_labels[0]

np.uint8(7)

**모델 성능 테스트**

In [ ]:
test_loss, test_acc = model.evaluate(test_images, test_labels)
print(f"test_acc: {test_acc}")
print(f"test_acc: {test_loss}")

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9766 - loss: 0.0778
test_acc: 0.9804999828338623
test_acc: 0.06613308191299438
